apiVersion: v1
kind: replication-controller
metadata: 
  name: mynginx-rc
spec: 
  replicas: 3
  selector: 
      app: mynginx  
  template:
    metadata: 
       labels:
          app: mynginx
    spec: 
      container: 
      - name: mynginx-container
        image: nginx 
        ports: 
        - containerPort: 80        